import Link from "next/link";
import { FlaskConical } from "lucide-react";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";

export const metadata = {
  title: "Development fallback",
  description: "Why a forecast on this deployment shows synthetic sources instead of web research.",
  robots: { index: false, follow: false },
};

/**
 * Landing page for the fallback provider's source links.
 *
 * Fixture "sources" point at `/dev-research/<angle>` rather than at a real
 * publisher, so a synthetic evidence item can never be mistaken for a citation.
 * The optional catch-all gives each fixture a distinct URL — which also keeps
 * the pipeline's URL-based deduplication honest during local development.
 */
export default function DevResearchPage() {
  return (
    <>
      <Navbar />
      <main id="main" className="mx-auto min-h-[60vh] max-w-2xl px-4 py-16 sm:px-6 sm:py-24">
        <div className="flex size-11 items-center justify-center rounded-full border border-hedge/40 bg-hedge/[0.06]">
          <FlaskConical className="size-5 text-hedge" aria-hidden />
        </div>

        <h1 className="mt-6 text-3xl font-semibold leading-tight">
          This source isn&apos;t real
        </h1>
        <p className="mt-4 text-[15px] leading-relaxed text-muted">
          You followed a link from a forecast that was generated by Predictly&apos;s
          development fallback. No web research was performed: this deployment
          has no research API key configured, so the pipeline ran against local
          fixtures to prove it works end to end.
        </p>

        <div className="mt-8 space-y-4 rounded-card border border-line bg-surface p-5 text-sm leading-relaxed text-muted">
          <p className="font-medium text-fg">To enable real research</p>
          <p>
            Set <code className="font-mono text-xs text-faint">TAVILY_API_KEY</code> (or{" "}
            <code className="font-mono text-xs text-faint">BRAVE_SEARCH_API_KEY</code>) for web
            search, and <code className="font-mono text-xs text-faint">ANTHROPIC_API_KEY</code> for
            the reasoning steps. With both present, forecasts cite real sources and the
            fallback banner disappears.
          </p>
        </div>

        <Link href="/" className="mt-8 inline-block text-sm font-medium text-lime hover:text-lime-dim">
          Back to Predictly
        </Link>
      </main>
      <Footer />
    </>
  );
}
